# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Incremental Building Triggered By Push Events
on: repository_dispatch

jobs:
  build:
    name: Retrieve markdown files and deploy the website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up building
        run: |
          echo "${{ github.event.client_payload.repo }}"
          echo "${{ github.event.client_payload.ref }}"
          echo "${{ github.event.client_payload.sha }}"
          echo "${{ github.event.client_payload.download_type }}"
